<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use App\Settings\ChatSettings;
use Brackets\CraftablePro\Models\CraftableProUser;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;


class Conversation extends Model
{
    use HasFactory;

    protected $table = 'conversations';

    protected $fillable = [
        'created_by',
        'name',
        'type',
    ];

    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'created_by' => 'integer',
        ];
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(CraftableProUser::class, 'created_by');
    }

    public function messages(): HasMany
    {
        return $this->hasMany(Message::class);
    }

    public function latestMessage(): HasOne
    {
        return $this->hasOne(Message::class)->latestOfMany();
    }

    public function members(): BelongsToMany
    {
        $settings  = app(ChatSettings::class);
        $chatRoles = array_merge($settings->roles['staff'], [$settings->roles['client']]);

        return $this->belongsToMany(
            CraftableProUser::class,
            'conversation_members',
            'conversation_id',
            'user_id',
        )
            ->withPivot('joined_at', 'last_read_at')
            ->withTimestamps()
            ->whereHas('roles', fn (Builder $q) => $q
                ->where('guard_name', 'craftable-pro')
                ->whereIn('id', $chatRoles));
    }

    public function scopeForUser(Builder $query, CraftableProUser $user): Builder
    {
        return $query->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $user->id));
    }

    public function hasMember(CraftableProUser $user): bool
    {
        return $this->members()->where('craftable_pro_users.id', $user->id)->exists();
    }

    public function isVisibleTo(CraftableProUser $user): bool
    {
        return $user->hasAnyRole(app(ChatSettings::class)->roles['oversight']) || $this->hasMember($user);
    }

    /** Who may read its internal (staff-only) notes. */
    public function isInternalVisibleTo(CraftableProUser $user): bool
    {
        return $user->hasAnyRole(app(ChatSettings::class)->roles['staff']) && $this->isVisibleTo($user);
    }

    /** Create a message here, applying the chat visibility rules. */
    public function postMessage(CraftableProUser $sender, array $data): Message
    {
        $settings   = app(ChatSettings::class);
        $visibility = $data['visibility'] ?? $settings->default_visibility;

        // Only staff may post internal notes; anyone else is forced public.
        if ($visibility === $settings->visibility['internal'] && ! $sender->hasAnyRole($settings->roles['staff'])) {
            $visibility = $settings->visibility['public'];
        }

        $message = $this->messages()->create([
            'user_id'       => $sender->id,
            'body'          => $data['body'],
            'type'          => $settings->message_default_type,
            'visibility'    => $visibility,
            'reply_to_id'   => $data['reply_to_id'] ?? null,
            'private_to_id' => $settings->whispers_enabled ? ($data['private_to_id'] ?? null) : null,
        ]);

        $this->touch();

        return $message;
    }

    /** Record that the user has read up to now; returns the timestamp, or null if they aren't a member. */
    public function markReadBy(int $userId): ?Carbon
    {
        $readAt = now();

        return $this->members()->updateExistingPivot($userId, ['last_read_at' => $readAt])
            ? $readAt
            : null;
    }

    /** Remove a member from this conversation. */
    public function removeMember(int $userId): void
    {
        $this->members()->detach($userId);
    }

    /** Everyone who may see this conversation live: its members plus oversight users. */
    public function audienceIds(): Collection
    {
        return $this->members
            ->pluck('id')
            ->merge(CraftableProUser::role(app(ChatSettings::class)->roles['oversight'])->pluck('id'))
            ->map(fn ($id) => (int) $id)
            ->unique()
            ->values();
    }

    /**
     * Whose personal channel receives a freshly sent message. We pick the exact
     * recipients so an unauthorized socket never receives it: a whisper reaches
     * only its two parties, an internal note only the staff in the audience.
     *
     * @return array<int>
     */
    public function recipientIdsFor(Message $message): array
    {
        if ($message->private_to_id !== null) {
            return array_values(array_unique([
                (int) $message->user_id,
                (int) $message->private_to_id,
            ]));
        }

        $audience = $this->audienceIds();

        if ($message->isInternal()) {
            return CraftableProUser::role(app(ChatSettings::class)->roles['staff'])
                ->whereIn('id', $audience)
                ->pluck('id')
                ->map(fn ($id) => (int) $id)
                ->values()
                ->all();
        }

        return $audience->all();
    }

    public function scopePrivateBetween(Builder $query, int $userA, int $userB): Builder
    {
        return $query
            ->where('type', 'private')
            ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $userA))
            ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $userB))
            ->has('members', '=', 2);
    }

    public static function findOrCreatePrivateBetween(CraftableProUser $user, int $otherUserId): self
    {
        return DB::transaction(function () use ($user, $otherUserId) {
            return static::privateBetween($user->id, $otherUserId)->first()
                ?? tap(static::create([
                    'type'       => 'private',
                    'created_by' => $user->id,
                ]), fn (self $c) => $c->members()->attach(
                    [$user->id, $otherUserId],
                    ['joined_at' => now()],
                ));
        });
    }

    public static function supportFor(CraftableProUser $client): ?self
    {
        return DB::transaction(function () use ($client) {
            $existing = static::query()
                ->where('type', 'private')
                ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $client->id))
                ->whereHas('members', fn (Builder $q) => $q->role(app(ChatSettings::class)->roles['account_manager'])
                    ->where('craftable_pro_users.id', '!=', $client->id))
                ->first();

            if ($existing) {
                return $existing;
            }

            $am = static::nextAccountManager();

            return $am ? static::findOrCreatePrivateBetween($client, $am->id) : null;
        });
    }


    private static function nextAccountManager(): ?CraftableProUser
    {
        return User::role(app(ChatSettings::class)->roles['account_manager'])
            ->whereNull('craftable_pro_users.deleted_at')
            ->select('craftable_pro_users.*')
            ->selectSub(
                DB::table('conversation_members')
                    ->selectRaw('MAX(joined_at)')
                    ->whereColumn('conversation_members.user_id', 'craftable_pro_users.id'),
                'last_assigned_at',
            )
            ->orderBy('last_assigned_at')
            ->orderBy('craftable_pro_users.id')
            ->lockForUpdate()
            ->first();
    }
}
