<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Brackets\CraftablePro\Models\CraftableProUser;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\DB;


class Conversation extends Model
{
    use HasFactory;

    protected $table = 'conversations';

    protected $fillable = [
        'created_by',
        'name',
        'type',
    ];

    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'created_by' => 'integer',
        ];
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(CraftableProUser::class, 'created_by');
    }

    public function messages(): HasMany
    {
        return $this->hasMany(Message::class);
    }

    public function latestMessage(): HasOne
    {
        return $this->hasOne(Message::class)->latestOfMany();
    }

    public function members(): BelongsToMany
    {
        return $this->belongsToMany(
            CraftableProUser::class,
            'conversation_members',
            'conversation_id',
            'user_id',
        )
            ->withPivot('joined_at', 'last_read_at')
            ->withTimestamps();
    }

    public function scopeForUser(Builder $query, CraftableProUser $user): Builder
    {
        return $query->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $user->id));
    }

    public function scopePrivateBetween(Builder $query, int $userA, int $userB): Builder
    {
        return $query
            ->where('type', 'private')
            ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $userA))
            ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $userB))
            ->has('members', '=', 2);
    }

    public static function findOrCreatePrivateBetween(CraftableProUser $user, int $otherUserId): self
    {
        return DB::transaction(function () use ($user, $otherUserId) {
            return static::privateBetween($user->id, $otherUserId)->first()
                ?? tap(static::create([
                    'type'       => 'private',
                    'created_by' => $user->id,
                ]), fn (self $c) => $c->members()->attach(
                    [$user->id, $otherUserId],
                    ['joined_at' => now()],
                ));
        });
    }

    public static function supportFor(CraftableProUser $client): ?self
    {
        return DB::transaction(function () use ($client) {
            // The support thread is the private conversation that has both this
            // client and an account-manager. We intentionally do NOT require
            // exactly 2 members: a super-admin may have joined to oversee it.
            $existing = static::query()
                ->where('type', 'private')
                ->whereHas('members', fn (Builder $q) => $q->where('craftable_pro_users.id', $client->id))
                ->whereHas('members', fn (Builder $q) => $q->role(config('chat.roles.account_manager'))
                    ->where('craftable_pro_users.id', '!=', $client->id))
                ->first();

            if ($existing) {
                return $existing;
            }

            $am = static::nextAccountManager();

            return $am ? static::findOrCreatePrivateBetween($client, $am->id) : null;
        });
    }


    private static function nextAccountManager(): ?CraftableProUser
    {
        return User::role(config('chat.roles.account_manager'))
            ->whereNull('craftable_pro_users.deleted_at')
            ->select('craftable_pro_users.*')
            ->selectSub(
                DB::table('conversation_members')
                    ->selectRaw('MAX(joined_at)')
                    ->whereColumn('conversation_members.user_id', 'craftable_pro_users.id'),
                'last_assigned_at',
            )
            ->orderBy('last_assigned_at')
            ->orderBy('craftable_pro_users.id')
            ->lockForUpdate()
            ->first();
    }
}
