<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Brackets\CraftablePro\Models\CraftableProUser;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Message extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'messages';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'conversation_id',
        'user_id',
        'reply_to_id',
        'body',
        'type',
        'visibility',
        'private_to_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'conversation_id' => 'integer',
        'user_id' => 'integer',
        'reply_to_id' => 'integer',
        'private_to_id' => 'integer',
    ];
    }

    /** Only messages the client is allowed to see. */
    public function scopePublic(Builder $query): Builder
    {
        return $query->where('visibility', config('chat.visibility.public'));
    }

    public function isInternal(): bool
    {
        return $this->visibility === config('chat.visibility.internal');
    }

    /** A whisper is a private message visible only to its sender and one recipient. */
    public function isWhisper(): bool
    {
        return $this->private_to_id !== null;
    }

    /**
     * Hide whispers from everyone except the two parties: a message is visible
     * when it is not a whisper, or the viewer is the sender or the recipient.
     */
    public function scopeVisibleTo(Builder $query, int $userId): Builder
    {
        return $query->where(fn (Builder $q) => $q
            ->whereNull('private_to_id')
            ->orWhere('user_id', $userId)
            ->orWhere('private_to_id', $userId));
    }

    public function conversation(): BelongsTo
    {
        return $this->belongsTo(Conversation::class);
    }

    public function sender(): BelongsTo
    {
        return $this->belongsTo(CraftableProUser::class, 'user_id');
    }

    public function replyTo(): BelongsTo
    {
        return $this->belongsTo(self::class, 'reply_to_id');
    }

    /** The single user a whisper is addressed to (null for ordinary messages). */
    public function recipient(): BelongsTo
    {
        return $this->belongsTo(CraftableProUser::class, 'private_to_id');
    }
}
